### ISSUE TITLE
Flask Configuration Limits - Option To Modify

### ISSUE THREAD

**Issue by doughoke** [temal-/clamav-rest#32]
This is really 2 fold...

1) Sometimes files maybe larger than the default size limit of flask and therefore the timeouts need to be extended.

I suggest modifying config.py to hold defaults for BODY_TIMEOUT,  RESPONSE_TIMEOUT, and MAX_CONTENT_LENGTH. These can then be overwritten as environment variables and lazy loaded into the container on runtime.

2) Bumping alpine container to remove some critical vulns in version python:3.10-alpine3.13 to 3.10-alpine3.15

I have a fork and will test it out before PR if you accept the issues.

**Comment by maltekrupa** [comment]
Hi,

both are valid points. 👍

1. sounds relatively straight forward.
2. I had some issues with a quart dependency and alpine containers > 3.13 in the past but let's see if we can make it work somehow.

**Comment by maltekrupa** [comment]
Hey,

I already did 2. in #33. :)

Malte

**Comment by maltekrupa** [comment]
Hey,

fyi: `MAX_CONTENT_LENGTH` was added in #35.

Malte

**Comment by maltekrupa** [comment]
Closed with #42 

Thank you!
